<a href="https://colab.research.google.com/github/TaeTToBBi/TaeTToBBi/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 교수님 사랑합니다...♥

2. 1×1=1
2×1=2
3×1=3
4×1=4
5×1=5
6×1=6
7×1=7
8×1=8
9×1=9
1×2=2
2×2=4
3×2=6
4×2=8
5×2=10
6×2=12
7×2=14
8×2=16
9×2=18
1×3=3
2×3=6
3×3=9
4×3=12
5×3=15
6×3=18
7×3=21
8×3=24
9×3=27
1×4=4
2×4=8
3×4=12
4×4=16
5×4=20
6×4=24
7×4=28
8×4=32
9×4=36
1×5=5
2×5=10
3×5=15
4×5=20
5×5=25
6×5=30
7×5=35
8×5=40
9×5=45
1×6=6
2×6=12
3×6=18
4×6=24
5×6=30
6×6=36
7×6=42
8×6=48
9×6=54
1×7=7
2×7=14
3×7=21
4×7=28
5×7=35
6×7=42
7×7=49
8×7=56
9×7=63
1×8=8
2×8=16
3×8=24
4×8=32
5×8=40
6×8=48
7×8=56
8×8=64
9×8=72
1×9=9
2×9=18
3×9=27
4×9=36
5×9=45
6×9=54
7×9=63
8×9=72
9×9=81

In [2]:
print("♥구구단을 출력합니다♡.\n")
for x in range(1, 10):
    print("------- [" + str(x) + "단] -------")
    for y in range(1, 10):
        print(x, "X", y, "=", x*y)
print("---------------------")

♥구구단을 출력합니다♡.

------- [1단] -------
1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9
------- [2단] -------
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
------- [3단] -------
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
------- [4단] -------
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
------- [5단] -------
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
------- [6단] -------
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
------- [7단] -------
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
------- [8단] -------
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
------- [9단] -------
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
---------------------

3.당신의 성적은 100이므로 점수는 A입니다.
당신의 성적은 50이므로 점수는 F입니다.
당신의 성적은 70이므로 점수는 C입니다.
당신의 성적은 80이므로 점수는 B입니다.
당신의 성적은 80이므로 점수는 B입니다.
당신의 성적은 70이므로 점수는 C입니다.
당신의 성적은 60이므로 점수는 D입니다.
당신의 성적은 70이므로 점수는 C입니다.
당신의 성적은 50이므로 점수는 F입니다.
당신의 성적은 70이므로 점수는 C입니다.
당신의 성적은 80이므로 점수는 B입니다.

4.
i의 값 : 1, 합계 : 1
i의 값 : 2, 합계 : 3
i의 값 : 3, 합계 : 6
i의 값 : 4, 합계 : 10
i의 값 : 5, 합계 : 15
i의 값 : 6, 합계 : 21
i의 값 : 7, 합계 : 28
i의 값 : 8, 합계 : 36
i의 값 : 9, 합계 : 45
i의 값 : 10, 합계 : 55

중국집에서 주문을 한다. 짜장면 한그릇은 10,000원 이다. 입력 금액이 짜장면 한 그릇 보다 많으면 구매가능 아니면 구매 불가능으로 나타내시오.

1학년때는 자유전공, 2학년때는 과이름 바뀌고 배우는거 바뀌기 전, 그다음 군대를 다녀온 후 3학년2학기부터 복학함으로써 아무것도 모르는 상태로 4학년 겸 3학년이지만 열심히 해보겠습니다. 많이 알려주시면 감사하겠습니다.